"""add_book_versions_table

Revision ID: 348d466cdb24
Revises: ad76a4d0afdf
Create Date: 2026-01-15 21:28:58.603989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '348d466cdb24'
down_revision: Union[str, Sequence[str], None] = 'ad76a4d0afdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. 创建 book_versions 表
    op.create_table('book_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_format', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_book_versions_file_format'), 'book_versions', ['file_format'], unique=False)
    op.create_index(op.f('ix_book_versions_file_hash'), 'book_versions', ['file_hash'], unique=True)
    op.create_index(op.f('ix_book_versions_id'), 'book_versions', ['id'], unique=False)
    
    # 2. 迁移现有数据：将 books 表的文件信息复制到 book_versions
    # 每本书作为自己的第一个（主）版本
    op.execute("""
        INSERT INTO book_versions (
            book_id, file_path, file_name, file_format, file_size, file_hash,
            quality, source, is_primary, added_at
        )
        SELECT 
            id, file_path, file_name, file_format, file_size, file_hash,
            'medium', NULL, 1, added_at
        FROM books
        WHERE file_path IS NOT NULL
    """)
    
    # 3. 删除 books 表的文件相关字段
    op.drop_index(op.f('ix_books_file_format'), table_name='books')
    op.drop_index(op.f('ix_books_file_hash'), table_name='books')
    
    # SQLite 不支持直接删除列，需要重建表
    # 创建临时表
    op.execute("""
        CREATE TABLE books_new (
            id INTEGER PRIMARY KEY,
            library_id INTEGER NOT NULL,
            title VARCHAR(200) NOT NULL,
            author_id INTEGER,
            cover_path VARCHAR(500),
            description TEXT,
            publisher VARCHAR(100),
            age_rating VARCHAR(20) DEFAULT 'general',
            content_warning TEXT,
            added_at DATETIME,
            FOREIGN KEY(library_id) REFERENCES libraries(id),
            FOREIGN KEY(author_id) REFERENCES authors(id)
        )
    """)
    
    # 复制数据（不包含文件字段）
    op.execute("""
        INSERT INTO books_new (
            id, library_id, title, author_id, cover_path, description,
            publisher, age_rating, content_warning, added_at
        )
        SELECT 
            id, library_id, title, author_id, cover_path, description,
            publisher, age_rating, content_warning, added_at
        FROM books
    """)
    
    # 删除旧表
    op.execute("DROP TABLE books")
    
    # 重命名新表
    op.execute("ALTER TABLE books_new RENAME TO books")
    
    # 重建索引
    op.create_index(op.f('ix_books_added_at'), 'books', ['added_at'], unique=False)
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('file_path', sa.VARCHAR(length=1000), nullable=False))
    op.add_column('books', sa.Column('file_size', sa.INTEGER(), nullable=False))
    op.add_column('books', sa.Column('file_hash', sa.VARCHAR(length=64), nullable=False))
    op.add_column('books', sa.Column('file_name', sa.VARCHAR(length=255), nullable=False))
    op.add_column('books', sa.Column('file_format', sa.VARCHAR(length=20), nullable=False))
    op.create_index(op.f('ix_books_file_hash'), 'books', ['file_hash'], unique=False)
    op.create_index(op.f('ix_books_file_format'), 'books', ['file_format'], unique=False)
    op.drop_index(op.f('ix_book_versions_id'), table_name='book_versions')
    op.drop_index(op.f('ix_book_versions_file_hash'), table_name='book_versions')
    op.drop_index(op.f('ix_book_versions_file_format'), table_name='book_versions')
    op.drop_table('book_versions')
    # ### end Alembic commands ###
