"""add_filename_patterns_table

Revision ID: a65cf1a541fe
Revises: 3c23c394a5ac
Create Date: 2026-01-15 22:44:57.579413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65cf1a541fe'
down_revision: Union[str, Sequence[str], None] = '3c23c394a5ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filename_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('regex_pattern', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('accuracy_rate', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('example_filename', sa.String(length=500), nullable=True),
    sa.Column('example_result', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filename_patterns_created_at'), 'filename_patterns', ['created_at'], unique=False)
    op.create_index(op.f('ix_filename_patterns_id'), 'filename_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_filename_patterns_is_active'), 'filename_patterns', ['is_active'], unique=False)
    op.create_index(op.f('ix_filename_patterns_priority'), 'filename_patterns', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filename_patterns_priority'), table_name='filename_patterns')
    op.drop_index(op.f('ix_filename_patterns_is_active'), table_name='filename_patterns')
    op.drop_index(op.f('ix_filename_patterns_id'), table_name='filename_patterns')
    op.drop_index(op.f('ix_filename_patterns_created_at'), table_name='filename_patterns')
    op.drop_table('filename_patterns')
    # ### end Alembic commands ###
